### ISSUE TITLE
Does not remember user settings

### ISSUE THREAD

**Issue by razzeee** [flathub/net.filebot.FileBot#4]
This seems to forget the user settings between restarts.

@rednoah am I missing some variable to set the correct folder or where would settings normally be stored?

**Comment by rednoah** [comment]
What's the startup configuration? The user settings are stored differently depending on the OS (e.g. Registry on Windows) and startup configuration (e.g. normal package vs portable package).

My first guess would be `~/.filebot` or `~/.java/.userPrefs`:
https://stackoverflow.com/questions/1320709/preference-api-storage

The portable `filebot.sh` script will explicitly force a specific storage engine and file location, so I would do the same in the flatpack to make things explicitly clear:
```
-Djava.util.prefs.PreferencesFactory=net.filebot.util.prefs.FilePreferencesFactory -Dnet.filebot.util.prefs.file="$APP_DATA/prefs.properties"
```

**Comment by razzeee** [comment]
That seems to fix the problem, thank you!
